### ISSUE TITLE
Broken Downloads

### ISSUE THREAD

**Issue by Viiiinx** [Metaphysics0/songsterr-downloader#29]
Hi, I converted a tab to a gp5 file but Guitar Pro sait that it was broken. 
Here are the tabs I tried: https://tabs.ultimate-guitar.com/tab/3teeth/merchant-of-the-void-tabs-4783706
https://tabs.ultimate-guitar.com/tab/rammstein/ohne-dich-tabs-2445143

**Comment by Metaphysics0** [comment]
checking

**Comment by Metaphysics0** [comment]
These are not guitar pro tabs, these are just text submitted tabs.


The web app works for ultimate guitar tabs that have `guitar pro` specified by ultimate guitar.

See screenshots

<img width="1066" alt="Screenshot 2023-12-27 at 20 58 37" src="https://github.com/Metaphysics0/songsterr-downloader/assets/47161696/156de8c5-3710-44bc-902e-6cf24ea92be3">
<img width="1066" alt="Screenshot 2023-12-27 at 20 58 44" src="https://github.com/Metaphysics0/songsterr-downloader/assets/47161696/21e01b1c-f9f5-490c-89fe-a6e606c60ba4">
