### ISSUE TITLE
Wrong Song Downloaded

### ISSUE THREAD

**Issue by lorthirk** [Metaphysics0/songsterr-downloader#33]
Hello, 

I'm trying to download this song https://www.songsterr.com/a/wsa/seether-careless-whisper-original-bass-tab-s504684 but apparently a completely different one is downloaded.

**Comment by cplprince** [comment]
same issue here... looks like it downloads wrong instrument

**Comment by lorthirk** [comment]
Actually I did some more investigation this morning. I came to the conclusion that somehow the linked GP file is simply another song, I don't know how could that happen. I reported the file and apparently this revision has been taken down now. So I'd say it's not an issue of the downloader. For me the issue can be closed.

**Comment by Metaphysics0** [comment]
Thanks for your help @lorthirk @cplprince
